# Generated by Django 5.0.6 on 2024-05-24 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('house_type', models.CharField(choices=[('duplex', 'Duplex'), ('apartment', 'Apartment'), ('villa', 'Villa'), ('other', 'Other')], max_length=20)),
                ('other_type', models.CharField(blank=True, max_length=100, null=True)),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('balcony', models.BooleanField(default=False)),
                ('swimming_pool', models.BooleanField(default=False)),
                ('playing_area', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
